-- Custom SQL migration file, put your code below! --
-- Seed card batch

INSERT INTO "cards" (
  "id", "card_code", "name", "rarity", "special_rarity", "element", "card_type",
  "attack", "health", "gate_points", "ikz_cost", "keywords", "subtypes",
  "effect_text", "flavor_text", "image_url"
) VALUES
(
  gen_random_uuid()::uuid,
  'AZK01-001',
  'Penny',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  0,
  1,
  0,
  1,
  ARRAY['Defender'],
  ARRAY['Beanz'],
  '[Defender] (If this card is in the Garden, you may tap it to redirect an attack to this card)',
  NULL,
  'S1-AZK01-001_Penny_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-002',
  'Healing Flutter',
  'UC',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Beanz'],
  '[Main] Heal 2 to your leader',
  NULL,
  'S1-AZK01-002_Healing-Flutter_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-003',
  'Black Jade Courier',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  0,
  1,
  ARRAY[]::text[],
  ARRAY['Black Jade', 'Strider'],
  '[On Play] Look at the top 5 cards of your deck, reveal up to 1 Black Jade subtype card other than Black Jade Courier and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-AZK01-003_Black-Jade-Courier_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-004',
  'Alley Thug',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  0,
  1,
  ARRAY[]::text[],
  ARRAY['Alley Dweller', 'Dawnling'],
  '[When Attacking] This card gets +1 attack until the end of the turn.',
  NULL,
  'S1-AZK01-004_Alley-Thug_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-005',
  'Caravan Guard',
  'UC',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  2,
  1,
  4,
  ARRAY[]::text[],
  ARRAY['Samurai', 'Steelborn'],
  '[On Play] Deal up to 1 damage to an entity in your opponent''s Garden.',
  NULL,
  'S1-AZK01-005_Caravan-Guard_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-006',
  'Gus',
  'R',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Beanz', 'Trickster'],
  '[When Attacked] You may return this card to your hand.',
  NULL,
  'S1-AZK01-006_Gus_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-007',
  'Johnny',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  0,
  2,
  ARRAY[]::text[],
  ARRAY['Beanz', 'Invigorate'],
  '[On Play] Give an entity in your Garden +1 attack until the end of the turn.',
  NULL,
  'S1-AZK01-007_Johnny_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-008',
  'Rainy Day Assassin',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  1,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Assassin'],
  '[On Play] You may sacrifice this card: Destroy an entity with a cost of 3 or less in your opponent''s Garden.',
  NULL,
  'S1-AZK01-008_Rainy-Day-Assassin_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-009',
  'The Red Bean',
  'R',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Legendary Bean'],
  '[Main] Give an entity with a cost of 4 or less Charge (Can attack the same turn it enters the Garden) until the end of the turn.',
  NULL,
  'S1-AZK01-009_The-Red-Bean_S_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-010',
  'JD',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Dawnling', 'JD'],
  'If you only have (Normal) entities in your Garden, this card has +2 attack.',
  NULL,
  'S1-AZK01-010_JD_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-011',
  'Rooftop Hunter',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  1,
  1,
  3,
  ARRAY['Charge'],
  ARRAY['Steelborn'],
  'Charge (Can attack the same turn it enters the Garden). [Garden Only Ability] If this card is untapped at the end of your turn, sacrifice it.',
  NULL,
  'S1-AZK01-011_Rooftop-Hunter_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-012',
  'Ed',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  3,
  3,
  1,
  4,
  ARRAY[]::text[],
  ARRAY['Beanz'],
  NULL,
  NULL,
  'S1-AZK01-012_Ed_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-014',
  'Trade Guild Cavalry',
  'R',
  NULL,
  'NORMAL',
  'ENTITY',
  3,
  3,
  2,
  5,
  ARRAY[]::text[],
  ARRAY['Invigorate', 'Samurai'],
  '[When Attacking] Give another entity in your Garden +2 attack until the end of the turn.',
  NULL,
  'S1-AZK01-014_Trade-Guild-Cavalry_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-015',
  'Mo',
  'SR',
  NULL,
  'NORMAL',
  'ENTITY',
  4,
  4,
  1,
  6,
  ARRAY[]::text[],
  ARRAY['Dawnling', 'Fox Fire'],
  '[On Play] If your leader is (Water), untap 1 IKZ. If your leader is (Earth), heal 2 to your leader. If your leader is (Lightning), gain Charge (Can attack the same turn it enters the Garden) until the end of the turn. If your leader is (Fire), deal 2 damage to target leader.',
  NULL,
  'S1-AZK01-015_Mo_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-016',
  'Sleight of Hand',
  'C',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Trickster'],
  '[Main] Draw 2, then discard 2.',
  NULL,
  'S1-AZK01-016_Sleight-of-Hand_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-017',
  'Hook Sword Strike',
  'UC',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Steelborn'],
  '[Main] Deal up to 1 damage to an entity in any Garden and up to 1 damage to a leader.',
  NULL,
  'S1-AZK01-017_Hook-Sword-Strike_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-018',
  'Monk Staff of Warding',
  'C',
  NULL,
  'NORMAL',
  'WEAPON',
  3,
  NULL,
  NULL,
  4,
  ARRAY[]::text[],
  ARRAY['Staff'],
  'Leaders equipped with this card take 1 less damage from combat.',
  NULL,
  'S1-AZK01-018_Monk-Staff-of-Warding_W_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-019',
  'Jay',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  1,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Beanz'],
  'If you only have (Normal) entities in your Garden, this card has +2 health.',
  NULL,
  'S1-AZK01-019_Jay_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-020',
  'Power of Friendship',
  'R',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  3,
  ARRAY[]::text[],
  ARRAY['Beanz', 'JD'],
  '[Main] Give 2 entities in your Garden each +1 attack until the end of the turn. [Response] Give 2 entities in your Garden each +1 health until the end of the turn.',
  NULL,
  'S1-AZK01-020_Power-of-Friendship_S_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-021',
  'Mizuto',
  'C',
  NULL,
  'WATER',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Wavecaller'],
  '[On Play] Look at the top 5 cards of your deck, reveal up to 1 Driftward subtype card and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-AZK01-021_Mizuto_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-022',
  'Mirage Frog',
  'UC',
  NULL,
  'WATER',
  'ENTITY',
  1,
  2,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Frog', 'Rippleborn', 'Watercrafting'],
  '[On Play] You may discard 1: Return an entity with a cost of 2 or less in any Garden to its owner''s hand.',
  NULL,
  'S1-AZK01-022_Mirage-Frog_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-023',
  'Maho',
  'C',
  NULL,
  'WATER',
  'ENTITY',
  1,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Wavecaller'],
  '[In Garden Only Ability][End of Your Turn] If you have 2 or less cards in your hand, draw 1.',
  NULL,
  'S1-AZK01-023_Maho_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-024',
  'Fumiko',
  'UC',
  NULL,
  'WATER',
  'ENTITY',
  1,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Painter', 'Watercrafting'],
  '[On Play] You may return an entity in your Garden to your hand: Play an entity with a cost of 2 or less from your hand.',
  NULL,
  'S1-AZK01-024_Fumiko_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-025',
  'Lighthouse Keeper',
  'UC',
  NULL,
  'WATER',
  'ENTITY',
  0,
  3,
  0,
  4,
  ARRAY['Defender', 'Effect Immune'],
  ARRAY['Driftward', 'Elder'],
  'Defender. This card cannot take damage from card effects.',
  NULL,
  'S1-AZK01-025_Lighthouse-Keeper_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-026',
  'Moonlit Crane',
  'C',
  NULL,
  'WATER',
  'ENTITY',
  2,
  2,
  2,
  5,
  ARRAY[]::text[],
  ARRAY['Bird', 'Driftward', 'Rippleborn'],
  '[Response][Once/Turn] You may discard 1: Reduce a leader''s or an entity''s attack by 1 until the end of the turn.',
  NULL,
  'S1-AZK01-026_Moonlit-Crane_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-027',
  'Kaiya Mizumi',
  'R',
  NULL,
  'WATER',
  'ENTITY',
  3,
  3,
  2,
  6,
  ARRAY[]::text[],
  ARRAY['Wavecaller'],
  '[On Play] You may discard up to 4 cards: Draw cards equal to the number of cards you discarded.',
  NULL,
  'S1-AZK01-027_Kaiya-Mizumi_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-028',
  'Soryu no Rin',
  'SR',
  NULL,
  'WATER',
  'ENTITY',
  7,
  7,
  2,
  8,
  ARRAY[]::text[],
  ARRAY['Watercrafting', 'Wavecaller'],
  '[On Play] You must discard your hand: Return all other entities in each player''s Garden to their owner''s hands.',
  NULL,
  'S1-AZK01-028_Soryu-no-Rin_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-029',
  'Aquatic Veil',
  'R',
  NULL,
  'WATER',
  'SPELL',
  NULL,
  NULL,
  NULL,
  0,
  ARRAY[]::text[],
  ARRAY['Aquashield'],
  '[Response] Discard 2: Reduce a leader''s or an entity''s attack by 3 until the end of the turn.',
  NULL,
  'S1-AZK01-029_Aquatic-Veil_S_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-030',
  'Lotus of Paradise',
  'C',
  NULL,
  'WATER',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Lotus', 'Watercrafting'],
  '[Response] Untap up to 2 IKZ.',
  NULL,
  'S1-AZK01-030_Lotus-of-Paradise_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-031',
  'Tidal Insight',
  'UC',
  NULL,
  'WATER',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Sirencall'],
  '[Main] Look at the top 3 cards of your deck, reveal up to 1 Water card and add it to your hand, then put the rest on the top or bottom of your deck in any order.',
  NULL,
  'S1-AZK01-031_Tidal-Insight_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-032',
  'Rippling Recall',
  'C',
  NULL,
  'WATER',
  'SPELL',
  NULL,
  NULL,
  NULL,
  3,
  ARRAY[]::text[],
  ARRAY['Watercrafting'],
  '[Main] Return an entity with a cost of 2 or more in your Garden to your hand: Return up to 1 entity with a cost of 4 or less in your opponent''s Garden to its owner''s hand.',
  NULL,
  'S1-AZK01-032_Rippling-Recall_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-033',
  'Elder Hoshin',
  'C',
  NULL,
  'LIGHTNING',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Elder', 'Monk', 'Stormcaller'],
  '[On Play] Look at the top 5 cards of your deck, reveal up to 1 Steelborn subtype card and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-AZK01-033_Elder-Hoshin_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-034',
  'Kira',
  'C',
  NULL,
  'LIGHTNING',
  'ENTITY',
  1,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Voltguard'],
  '[In Alley Only Ability] Whenever an entity in your Garden is attacked, you may swap that entity and this card, then make this card the new attack target.',
  NULL,
  'S1-AZK01-034_Kira_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-035',
  'Raimaru the Stolen',
  'C',
  NULL,
  'LIGHTNING',
  'ENTITY',
  0,
  1,
  0,
  3,
  ARRAY['Defender'],
  ARRAY['Cat', 'Statue', 'Voltguard'],
  'Defender. This card can be played as a [Response].',
  NULL,
  'S1-AZK01-035_Raimaru-the-Stolen_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-036',
  'Denmu',
  'UC',
  NULL,
  'LIGHTNING',
  'ENTITY',
  2,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Bat', 'Shockcoil'],
  '[When Attacked] The attacking leader or entity becomes Shocked. (Does not untap during its next untap phase.)',
  NULL,
  'S1-AZK01-036_Denmu_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-037',
  'Stormcaller Tenkichi',
  'R',
  NULL,
  'LIGHTNING',
  'ENTITY',
  3,
  2,
  0,
  4,
  ARRAY['Charge'],
  ARRAY['Riftwalk', 'Stormcaller'],
  'Charge. This card can attack untapped or tapped entities in your opponent''s Alley.',
  NULL,
  'S1-AZK01-037_Stormcaller-Tenkichi_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-038',
  'Riven Flashborne',
  'R',
  NULL,
  'LIGHTNING',
  'ENTITY',
  2,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Riftwalk'],
  'This card can attack untapped or tapped entities in your opponent''s Alley.',
  NULL,
  'S1-AZK01-038_Riven-Flashborne_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-039',
  'Piko',
  'C',
  NULL,
  'LIGHTNING',
  'ENTITY',
  2,
  3,
  0,
  4,
  ARRAY[]::text[],
  ARRAY['Cat', 'Steelborn'],
  '[When Equipped] Gain Charge.',
  NULL,
  'S1-AZK01-039_Piko_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-040',
  'Black Jade Vault Master',
  'UC',
  NULL,
  'LIGHTNING',
  'ENTITY',
  1,
  3,
  2,
  5,
  ARRAY['Defender'],
  ARRAY['Black Jade', 'Tiger', 'Voltguard'],
  'Defender. [When Attacked] Deal up to 1 damage to a leader.',
  NULL,
  'S1-AZK01-040_Black-Jade-Vault-Master_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-041',
  'Wu Cha',
  'SR',
  NULL,
  'LIGHTNING',
  'ENTITY',
  7,
  7,
  2,
  8,
  ARRAY[]::text[],
  ARRAY['Fox Fire', 'Steelborn'],
  '[In Garden Only Ability][Once/Turn][Main] 1 IKZ: Equip up to 2 Weapon cards with a cost of 2 or less from your discard pile to this card.',
  NULL,
  'S1-AZK01-041_Wu-Cha_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-042',
  'Thunderclap',
  'SR',
  NULL,
  'LIGHTNING',
  'SPELL',
  NULL,
  NULL,
  NULL,
  5,
  ARRAY[]::text[],
  ARRAY['Stormcaller'],
  '[Main] Deal 3 damage, 2 damage, and 1 damage to 3 different entities in your opponent''s Garden.',
  NULL,
  'S1-AZK01-042_Thunderclap_S_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-043',
  'Stormglass Daggers',
  'C',
  NULL,
  'LIGHTNING',
  'WEAPON',
  1,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Dagger', 'Riftwalk'],
  'When equipped to a leader, the leader can attack untapped or tapped entities in your opponent''s Alley.',
  NULL,
  'S1-AZK01-043_Stormglass-Daggers_W_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-044',
  'Lightning Kanabo',
  'R',
  NULL,
  'LIGHTNING',
  'WEAPON',
  2,
  NULL,
  NULL,
  3,
  ARRAY[]::text[],
  ARRAY['Shockcoil'],
  '[Once/Turn] Whenever a leader or an entity equipped with this card deals combat damage to an opponent''s card, that card becomes Shocked. (Does not untap during its next untap phase.)',
  NULL,
  'S1-AZK01-044_Lightning-Kanabo_W_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-045',
  'Treetop Scout',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Scout'],
  '[On Play] Look at the top 5 cards of your deck, reveal up to 1 Obsidian subtype card and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-AZK01-045_Treetop-Scout_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-046',
  'Mina the Geomancer',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  1,
  0,
  1,
  ARRAY[]::text[],
  ARRAY['Earthfury'],
  'When this card enters the Garden, tap it. This entity cannot be untapped. [In Garden Only Ability][Start of Your Turn] Deal up to 1 damage to a leader.',
  NULL,
  'S1-AZK01-046_Mina-the-Geomancer_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-047',
  'Shiko the Priestess',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  2,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Earthwarden'],
  '[Once/Turn][When Attacking] Heal 1 to your leader.',
  NULL,
  'S1-AZK01-047_Shiko-the-Priestess_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-048',
  'Kale',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  2,
  2,
  3,
  ARRAY[]::text[],
  ARRAY['Obsidian'],
  'Carapace 1 (Reduce damage from all sources by 1. Carapace stacks.)',
  NULL,
  'S1-AZK01-048_Kale_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-049',
  'Lone Journeyman',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  2,
  2,
  3,
  ARRAY['Defender'],
  ARRAY['Earthwarden'],
  'Defender (If this card is in the Garden, you may tap it to redirect an attack to this card)',
  NULL,
  'S1-AZK01-049_Lone-Journeyman_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-050',
  'Shroom Tender',
  'R',
  NULL,
  'EARTH',
  'ENTITY',
  2,
  2,
  2,
  4,
  ARRAY[]::text[],
  ARRAY['Beanz', 'Earthwarden'],
  '[On Play] Heal 2 to your leader.',
  NULL,
  'S1-AZK01-050_Shroom-Tender_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-051',
  'Chillax',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  3,
  2,
  4,
  ARRAY['Defender'],
  ARRAY['Earthwarden', 'Sloth'],
  'Defender. [When Attacked] You may give another entity in your Garden +1 health until the end of the turn.',
  NULL,
  'S1-AZK01-051_Chillax_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-052',
  'Yojin',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  2,
  4,
  2,
  5,
  ARRAY[]::text[],
  ARRAY['Earthwarden'],
  'If the number of entities in your Garden is less than the number of entities in your opponent''s Garden, this card has Defender.',
  NULL,
  'S1-AZK01-052_Yojin_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-053',
  'Geodust Smuggler',
  'R',
  NULL,
  'EARTH',
  'ENTITY',
  4,
  5,
  3,
  7,
  ARRAY[]::text[],
  ARRAY['Obsidian'],
  '[In Garden Only Ability] As long as this card is in play, all other entities in your Garden have +1 health.',
  NULL,
  'S1-AZK01-053_Geodust-Smuggler_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-054',
  'Teb Fea',
  'SR',
  NULL,
  'EARTH',
  'ENTITY',
  7,
  7,
  2,
  8,
  ARRAY['Godmode'],
  ARRAY['Obsidian'],
  'Godmode (Cannot leave the field by taking damage or by card effects)',
  NULL,
  'S1-AZK01-054_Teb-Fea_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-055',
  'Earth Orb',
  'C',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Earthfury', 'Orb'],
  '[Response] Deal up to 1 damage to a leader or an entity in your opponent''s Garden and reduce that card''s attack by 1 until the end of the turn.',
  NULL,
  'S1-AZK01-055_Earth-Orb_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-056',
  'Glass Blower, Hokuto',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Artisan', 'Firemancer'],
  '[On Play] Look at the top 5 cards of your deck, reveal up to 1 Scorchweaver subtype card and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-AZK01-056_Glass-Blower-Hokuto_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-057',
  'Lounge Siren, Saeko',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Scorchweaver'],
  '[In Garden Only Ability][Start of Your Turn] You must deal 1 damage to an entity in your Garden and 1 damage to an entity in your opponent''s Garden.',
  NULL,
  'S1-AZK01-057_Lounge-Siren-Saeko_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-058',
  'Black Jade Warlord',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Black Jade', 'Blazerker', 'Invigorate'],
  '[After Attacking] You may sacrifice this card: Give a leader or an entity in your Garden +2 attack until the end of the turn.',
  NULL,
  'S1-AZK01-058_Black-Jade-Warlord_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-059',
  'Spice',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  2,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Chef', 'Pyreskin', 'Red Panda'],
  '[Once/Turn] Whenever this card takes damage, give another entity in your Garden +1 attack until the end of the turn.',
  NULL,
  'S1-AZK01-059_Spice_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-060',
  'Scarlett',
  'R',
  NULL,
  'FIRE',
  'ENTITY',
  3,
  2,
  2,
  5,
  ARRAY['Charge'],
  ARRAY['Blazerker'],
  '[When Attacking] You may give this card Infiltrate and +1 attack until the end of the turn. If you do, you must sacrifice this card at the end of the turn.',
  NULL,
  'S1-AZK01-060_Scarlett_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-061',
  'Firebrand Renji',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  3,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Pyreskin'],
  '[Once/Turn] Whenever this card takes damage from 3 different damage sources in one turn, deal up to 3 damage to a leader or an entity in any Garden.',
  NULL,
  'S1-AZK01-061_Firebrand-Renji_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-062',
  'Pekiro',
  'R',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  1,
  2,
  3,
  ARRAY[]::text[],
  ARRAY['Red Panda', 'Pyreskin'],
  '[Once/Turn] Whenever this card would take damage from an ability or spell, you may redirect that damage to another entity in any Garden.',
  NULL,
  'S1-AZK01-062_Pekiro_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-063',
  'Enzo',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  3,
  3,
  2,
  6,
  ARRAY[]::text[],
  ARRAY['Chef', 'Scorchweaver'],
  '[On Play] If this card is played in the Garden, deal up to 3 damage to a leader or an entity in any Garden.',
  NULL,
  'S1-AZK01-063_Enzo_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-064',
  'Zero',
  'SR',
  NULL,
  'FIRE',
  'ENTITY',
  7,
  7,
  2,
  8,
  ARRAY[]::text[],
  ARRAY['Black Jade', 'Scorchweaver'],
  'When this card enters the Garden, deal 2 damage to all entities in each player''s Garden.',
  NULL,
  'S1-AZK01-064_Zero_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-065',
  'Fire Orb',
  'C',
  NULL,
  'FIRE',
  'SPELL',
  NULL,
  NULL,
  NULL,
  4,
  ARRAY[]::text[],
  ARRAY['Orb', 'Scorchweaver'],
  '[Main] Deal 3 damage to your leader: Deal up to 5 damage to a leader or an entity in any Garden.',
  NULL,
  'S1-AZK01-065_Fire-Orb_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-066',
  'Firestorm',
  'UC',
  NULL,
  'FIRE',
  'SPELL',
  NULL,
  NULL,
  NULL,
  5,
  ARRAY[]::text[],
  ARRAY['Scorchweaver'],
  '[Main] Deal 2 damage to all leaders and entities in each player''s Garden.',
  NULL,
  'S1-AZK01-066_Firestorm_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-067',
  'Frida',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Beanz', 'Painter'],
  NULL,
  'Every color feels right today.',
  'S1-AZK01-067_Frida_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-068',
  'Pip',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Beanz'],
  '[On Play] When this card is played in the Alley, draw 1, then discard 1.',
  NULL,
  'S1-AZK01-068_Pip_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-069',
  'Link',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Beanz'],
  '[On Play] Look at the top 5 cards of your deck, reveal up to 1 Beanz subtype card and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-AZK01-069_Link_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-070',
  'Mocking Dummy',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  0,
  2,
  0,
  1,
  ARRAY[]::text[],
  ARRAY['Training Dummy'],
  '[In Garden Only Ability][Response] Tap this card and deal 1 damage to it: Reduce an opponent entity''s attack by 1 until the end of your opponent''s turn.',
  NULL,
  'S1-AZK01-070_Mocking-Dummy_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-071',
  'Alley Fetchduck',
  'UC',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  2,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Bird'],
  '[End of Your Turn] You may bottom deck this card: Draw 1.',
  NULL,
  'S1-AZK01-071_Alley-Fetchduck_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-072',
  'Beanz Mentor',
  'R',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Beanz', 'Elder'],
  '[When Attacking] Give another Beanz subtype entity in your Garden +1 attack until the end of the turn.',
  NULL,
  'S1-AZK01-072_Beanz-Mentor_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-073',
  'Top Beanz',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  1,
  2,
  3,
  ARRAY[]::text[],
  ARRAY['Beanz'],
  'If you only have Beanz subtype entities in your Garden, this card has +1 attack and +1 health.',
  NULL,
  'S1-AZK01-073_Top-Beanz_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-074',
  'Gurugumi Vanguard',
  'UC',
  NULL,
  'NORMAL',
  'ENTITY',
  0,
  2,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Gurijutsu'],
  '[Once/Turn][Main] This card''s attack becomes the attack of an entity in your opponent''s Garden until the end of the turn.',
  NULL,
  'S1-AZK01-074_Gurugumi-Vanguard_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-075',
  'Drunken Brewmaster',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  2,
  1,
  4,
  ARRAY[]::text[],
  ARRAY['Brewmaster', 'Elder'],
  '[Once/Turn] You may sacrifice 2 Beanz subtype entities in your Garden: This card gets +2 attack and +2 health until the end of the turn.',
  NULL,
  'S1-AZK01-075_Drunken-Brewmaster_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-077',
  'Stalking Assassin',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  2,
  2,
  3,
  ARRAY[]::text[],
  ARRAY['Assassin', 'Steelborn'],
  'This card can only attack leaders.',
  NULL,
  'S1-AZK01-077_Stalking-Assassin_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-078',
  'Fermented Beanz',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  2,
  2,
  4,
  ARRAY[]::text[],
  ARRAY['Beanz'],
  '[When Destroyed] Deal 1 damage to a leader or an entity in your opponent''s Garden.',
  NULL,
  'S1-AZK01-078_Fermented-Beanz_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-080',
  'Bladebound Ally',
  'R',
  NULL,
  'NORMAL',
  'ENTITY',
  3,
  2,
  3,
  5,
  ARRAY[]::text[],
  ARRAY['Invigorate', 'Samurai'],
  '[On Play] If this card is played in the Garden, give another entity in your Garden +2 attack until the end of the turn.',
  NULL,
  'S1-AZK01-080_Bladebound-Ally_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-081',
  'Gurugumi Mentor',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  3,
  3,
  2,
  5,
  ARRAY[]::text[],
  ARRAY['Gurijutsu'],
  'When this card is in your deck, it has all subtypes.',
  NULL,
  'S1-AZK01-081_Gurugumi-Mentor_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-082',
  'Black Jade Brawler',
  'UC',
  NULL,
  'NORMAL',
  'ENTITY',
  3,
  2,
  2,
  5,
  ARRAY['Charge'],
  ARRAY['Black Jade', 'Brawler', 'Steelborn'],
  'Charge (Can attack the same turn it enters the Garden.)',
  NULL,
  'S1-AZK01-082_Black-Jade-Brawler_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-084',
  'Good Enough Replica',
  'C',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Trickster'],
  '[Main] Return a Normal entity card with a cost of 6 or less from your discard pile to your hand.',
  NULL,
  'S1-AZK01-084_Good-Enough-Replica_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-085',
  'Invigorating Concoction',
  'C',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  3,
  ARRAY[]::text[],
  ARRAY['Beanz', 'Invigorate'],
  '[Main][Response] Give an entity in your Garden +2 attack until the end of the turn.',
  NULL,
  'S1-AZK01-085_Invigorating-Concoction_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-086',
  'Forging Tricks',
  'UC',
  NULL,
  'NORMAL',
  'SPELL',
  NULL,
  NULL,
  NULL,
  4,
  ARRAY[]::text[],
  ARRAY['Steelborn', 'Trickster'],
  '[Main] You may place up to 5 Weapon cards from your discard pile to the bottom of your deck in any order: Until the end of the turn, give your leader +1 attack for each card you bottom decked.',
  NULL,
  'S1-AZK01-086_Forging-Tricks_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-087',
  'Mizuryuu''s Torrent',
  'SR',
  NULL,
  'WATER',
  'SPELL',
  NULL,
  NULL,
  NULL,
  4,
  ARRAY[]::text[],
  ARRAY['Mizuryuu'],
  '[Main] Put up to 2 entities with a combined cost of 5 or less in your opponent''s Garden to the bottom of their owner''s deck in any order.',
  NULL,
  'S1-AZK01-087_Mizuryuus-Torrent_S_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-088',
  'Pulled Under',
  'R',
  NULL,
  'WATER',
  'SPELL',
  NULL,
  NULL,
  NULL,
  6,
  ARRAY[]::text[],
  ARRAY['Watercrafting'],
  '[Main] Put an entity with a cost of 7 or less in your opponent''s Garden to the bottom of its owner''s deck.',
  NULL,
  'S1-AZK01-088_Pulled-Under_S_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-089',
  'Mizuryuu Fist Master',
  'UC',
  NULL,
  'WATER',
  'ENTITY',
  5,
  5,
  3,
  7,
  ARRAY[]::text[],
  ARRAY['Frog', 'Mizuryuu', 'Watercrafting'],
  '[In Alley Only Ability][Main] You may bottom deck this card: Put up to 2 entity cards with a combined cost of 5 or less in your opponent''s Garden to the bottom of their owner''s deck in any order.',
  NULL,
  'S1-AZK01-089_Mizuryuu-Fist-Master_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-090',
  'Priestess of the Mists',
  'C',
  NULL,
  'WATER',
  'ENTITY',
  3,
  3,
  2,
  5,
  ARRAY[]::text[],
  ARRAY['Priestess', 'Wavecaller'],
  '[On Play] You may return an entity with a cost of 2 or less in your Garden to your hand.',
  NULL,
  'S1-AZK01-090_Priestess-of-the-Mists_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-091',
  'Bubble Adept',
  'UC',
  NULL,
  'WATER',
  'ENTITY',
  2,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Aquashield', 'Driftward'],
  '[In Garden Only Ability][Response] You may sacrifice this card: Reduce an entity''s attack by 1 until the end of your opponent''s turn.',
  NULL,
  'S1-AZK01-091_Bubble-Adept_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-092',
  'Lotus of Reflection',
  'C',
  NULL,
  'WATER',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Lotus', 'Wavecaller'],
  '[Main] Look at the top 5 cards of your deck, you may reveal a Water card with a cost of 2 or less and add it to your hand, then bottom deck the rest in any order. You may play the card from your hand.',
  NULL,
  'S1-AZK01-092_Lotus-of-Reflection_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-093',
  'Naiyara the Tideweaver',
  'R',
  NULL,
  'WATER',
  'ENTITY',
  4,
  4,
  3,
  7,
  ARRAY[]::text[],
  ARRAY['Downcurrent', 'Mizuryuu'],
  '[On Play] If this card is played in the Garden, put an entity with a cost of 4 or less in your opponent''s Garden to the bottom of its owner''s deck.',
  NULL,
  'S1-AZK01-093_Naiyara-the-Tideweaver_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-094',
  'Hidden Dagger',
  'C',
  NULL,
  'LIGHTNING',
  'WEAPON',
  1,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Dagger', 'Shadowfang'],
  'This card can be played as a Response.',
  NULL,
  'S1-AZK01-094_Hidden-Dagger_W_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-095',
  'Stormglass Katana',
  'C',
  NULL,
  'LIGHTNING',
  'WEAPON',
  3,
  NULL,
  NULL,
  4,
  ARRAY[]::text[],
  ARRAY['Riftwalk', 'Sword'],
  'When equipped to a leader, the leader can attack untapped or tapped entities in your opponent''s Alley.',
  NULL,
  'S1-AZK01-095_Stormglass-Katana_W_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-096',
  'Ninpo: Thunderstep',
  'UC',
  NULL,
  'LIGHTNING',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Voltguard'],
  '[Response] Swap an entity in your Garden with an entity in your Alley. If the other entity being swapped out is the target of an attack, the Alley entity being swapped into the Garden becomes the new target.',
  NULL,
  'S1-AZK01-096_Ninpo-Thunderstep_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-097',
  'Black Jade Pawnbroker',
  'C',
  NULL,
  'LIGHTNING',
  'ENTITY',
  1,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Black Jade', 'Merchant', 'Steelborn'],
  '[On Play] Put 5 cards from the top of your deck into your discard pile. If any of the discarded cards are Weapon cards, you may add 1 of them to your hand.',
  NULL,
  'S1-AZK01-097_Black-Jade-Pawnbroker_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-098',
  'Arms Dealer, Kin',
  'C',
  NULL,
  'LIGHTNING',
  'ENTITY',
  2,
  2,
  1,
  4,
  ARRAY[]::text[],
  ARRAY['Merchant', 'Steelborn'],
  '[On Play] If this card is played in the Alley you may tap this card: Play a Weapon card with a cost of 3 or less from your hand.',
  NULL,
  'S1-AZK01-098_Arms-Dealer-Kin_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-100',
  'Raizan''s Riposte',
  'C',
  NULL,
  'LIGHTNING',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Raizan', 'Steelborn'],
  '[Response] Play from your discard pile a Weapon card with a cost of 2 or less.',
  NULL,
  'S1-AZK01-100_Raizans-Riposte_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-101',
  'Sand Stands Still',
  'SR',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  3,
  ARRAY[]::text[],
  ARRAY['Earthwarden'],
  '[Main][Response] Give an Earth entity in your Garden +3 health until the end of turn.',
  NULL,
  'S1-AZK01-101_Sand-Stands-Still_S_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-102',
  'Oathstone',
  'C',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Obsidian'],
  '[Response] Give an entity with a cost of 4 or less Carapace 1 until the end of turn.',
  NULL,
  'S1-AZK01-102_Oathstone_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-103',
  'Dropline Station',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  0,
  4,
  3,
  5,
  ARRAY[]::text[],
  ARRAY['Earthfury'],
  '[In Garden Only Ability] Sacrifice an untapped Earth entity in your Garden: Deal damage equal to the sacrificed card''s health to a leader, capped at 5 damage. If the sacrificed entity had 3 or more health, draw 1. (This ability is not affected by Cooldown)',
  NULL,
  'S1-AZK01-103_Dropline-Station_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-104',
  'Sanzu''s Envoy',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  4,
  4,
  3,
  6,
  ARRAY[]::text[],
  ARRAY['Stonemend', 'Verdant'],
  '[On Play] If this card is played in the Garden, you may discard 1: Heal 2 to your leader.',
  NULL,
  'S1-AZK01-104_Sanzus-Envoy_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-105',
  'Prickly Tumbleweed',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  3,
  2,
  4,
  ARRAY[]::text[],
  ARRAY['Earthfury'],
  '[In Garden Only Ability][Main] Sacrifice this card: Deal damage equal to this card''s health to a leader or an entity in your opponent''s Garden.',
  NULL,
  'S1-AZK01-105_Prickly-Tumbleweed_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-106',
  'Lord of Sands, Osunanami',
  'SR',
  NULL,
  'EARTH',
  'ENTITY',
  6,
  6,
  3,
  10,
  ARRAY[]::text[],
  ARRAY['Colossal', 'Sandstrider'],
  'When this card is in your hand, its cost is reduced by 1 for every entity with Defender in your Garden.',
  NULL,
  'S1-AZK01-106_Lord-of-Sands-Osunanami_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-107',
  'Offering to Stillstone',
  'C',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Verdant'],
  '[Main] Discard 1: If you do not have an IKZ token, add 1. The IKZ token expires at the end of the turn.',
  NULL,
  'S1-AZK01-107_Offering-to-Stillstone_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-108',
  'Crushing Weight',
  'R',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  5,
  ARRAY[]::text[],
  ARRAY['Earthfury'],
  '[Main] Deal damage equal to the health of an Earth entity in your Garden to a leader or an entity in your opponent''s Garden, capped at 5 damage.',
  NULL,
  'S1-AZK01-108_Crushing-Weight_S_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-109',
  'Rock Sloth',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  3,
  4,
  3,
  6,
  ARRAY[]::text[],
  ARRAY['Obsidian', 'Sloth'],
  'Carapace 1 (Reduce damage from all sources by 1. Carapace stacks.)',
  NULL,
  'S1-AZK01-109_Rock-Sloth_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-110',
  'Gluttonous Devourer, Kasha',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  2,
  2,
  4,
  ARRAY[]::text[],
  ARRAY['Loneflame', 'Red Panda'],
  '[When Attacking] You may sacrifice all other entities in your Garden: Until the end of the turn, this entity gains +1 attack for each entity sacrificed this way.',
  NULL,
  'S1-AZK01-110_Gluttonous-Devourer-Kasha_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-111',
  'Black Jade Decoy',
  'R',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Ashveil', 'Black Jade', 'Shikigami'],
  '[In Alley Only Ability][Main] You may sacrifice this card: Deal up to 2 damage to an entity in your opponent''s Garden, then you may play an entity with a cost of 2 or less from your hand in the Garden.',
  NULL,
  'S1-AZK01-111_Black-Jade-Decoy_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-112',
  'Enrai Shakunetsu',
  'SR',
  NULL,
  'FIRE',
  'ENTITY',
  4,
  3,
  2,
  6,
  ARRAY[]::text[],
  ARRAY['Blazerker', 'Loneflame'],
  '[On Play] You may sacrifice an untapped entity in your Garden: If you control no entities in the Garden, this entity gains Charge until the end of the turn.',
  NULL,
  'S1-AZK01-112_Enrai-Shakunetsu_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-113',
  'Cinderwake Pursuer',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Blazerker', 'Cinderwake'],
  '[On Play] If you played 2 other cards this turn, this entity gains Charge until the end of the turn.',
  NULL,
  'S1-AZK01-113_Cinderwake-Pursuer_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-114',
  'Omen Peddler',
  'R',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  1,
  0,
  3,
  ARRAY[]::text[],
  ARRAY['Elder', 'Scorchweaver'],
  '[On Play] If this card is played in the Alley, deal 2 damage to an entity in your opponent''s Garden.',
  NULL,
  'S1-AZK01-114_Omen-Peddler_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-115',
  'Crazed Arsonist',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  2,
  0,
  2,
  ARRAY[]::text[],
  ARRAY['Scorchweaver', 'Wildfire'],
  '[When Attacking] You must deal 1 damage to all leaders. [When Sacrificed] You must deal 1 damage to all leaders.',
  NULL,
  'S1-AZK01-115_Crazed-Arsonist_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-116',
  'Tenmoku Daiki',
  'R',
  NULL,
  'FIRE',
  'ENTITY',
  3,
  2,
  3,
  4,
  ARRAY['Charge'],
  ARRAY['Blazerker', 'Brawler'],
  'Charge (Can attack the same turn it enters the Garden). [On Play] You must deal 3 damage to your leader.',
  NULL,
  'S1-AZK01-116_Tenmoku-Daiki_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-117',
  'Ignition Pact',
  'UC',
  NULL,
  'FIRE',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Blazerker'],
  '[Main] Deal 2 damage to your leader: Give an entity with a cost of 5 or less Charge until the end of the turn.',
  NULL,
  'S1-AZK01-117_Ignition-Pact_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-118',
  'Bandit Ringleader',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  2,
  2,
  4,
  ARRAY[]::text[],
  ARRAY['Bandit', 'Scorchweaver'],
  '[On Play] You may deal 1 damage to an entity in your Garden: If you played 2 other cards this turn, deal up to 2 damage to an entity in your opponent''s Garden.',
  NULL,
  'S1-AZK01-118_Bandit-Ringleader_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-119',
  'Piko of Thousand Blades',
  'L',
  NULL,
  'LIGHTNING',
  'LEADER',
  NULL,
  20,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Cat', 'Steelborn'],
  '[Once/Turn][Main] Pay 3 IKZ: Until the end of the turn, an entity in your Garden that is equipped with a Weapon card gets +1 attack for each Weapon card in your discard pile, capped at +3 attack.',
  NULL,
  'S1-AZK01-119A_Piko-of-Thousand-Blades_L_L_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-120',
  'Stormchain Gate',
  'G',
  NULL,
  'LIGHTNING',
  'GATE',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Portal an untapped entity from the Alley into the Garden: You may re-equip a weapon in your Garden with a cost equal to or less than the Gate Power of the portaled entity to a different leader or entity in your Garden.',
  NULL,
  'S1-AZK01-120_Stormchain-Gate_G_G_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-121',
  'Kagoro of the Burnt Path',
  'L',
  NULL,
  'FIRE',
  'LEADER',
  NULL,
  20,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Loneflame', 'Red Panda'],
  '[Once/Turn][Main] Pay 1 IKZ: This card gains +1 attack for each entity you played this turn, capped at +2 attack, until the end of the turn.',
  NULL,
  'S1-AZK01-121A_Kagoro-of-the-Burnt-Path_L_L_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-122',
  'Rushfire Gate',
  'G',
  NULL,
  'FIRE',
  'GATE',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Portal an untapped entity from the Alley into the Garden, then you may play an entity with a cost equal to or less than the Gate Power of the portaled entity from your hand and give it Charge until the end of the turn, then you must sacrifice that card at the end of the turn.',
  NULL,
  'S1-AZK01-122_Rushfire-Gate_G_G_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-123',
  'Goro Graveloth',
  'L',
  NULL,
  'EARTH',
  'LEADER',
  NULL,
  20,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Obsidian', 'Sloth'],
  '[Once/Turn][Main] Pay 1 IKZ: Give an entity in your Garden +1 health until the end of the turn.',
  NULL,
  'S1-AZK01-123A_Goro-Graveloth_L_L_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-124',
  'Gate of Devotion',
  'G',
  NULL,
  'EARTH',
  'GATE',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Portal an untapped entity from the Alley into the Garden, then you may sacrifice another untapped entity in your Garden with a cost equal to or less than the Gate Power of the portaled entity. If you do, you may deal damage to an entity in your opponent''s Garden equal to the health of the sacrificed entity.',
  NULL,
  'S1-AZK01-124_Gate-of-Devotion-Gate_G_G_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-125',
  'Benzai the Sly',
  'L',
  NULL,
  'WATER',
  'LEADER',
  NULL,
  20,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Frog', 'Merchant', 'Watercrafting'],
  '[Once/Turn][Main][Response] Pay 1 IKZ: If you discarded a card this turn, the next card you play this turn costs 2 less IKZ.',
  NULL,
  'S1-AZK01-125A_Benzai-the-Sly_L_L_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-126',
  'Gate of Echoed Waves',
  'G',
  NULL,
  'WATER',
  'GATE',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Portal an untapped entity from the Alley into the Garden: Return a spell card with a cost equal to or less than the Gate Power of the portaled entity from your discard pile to your hand.',
  NULL,
  'S1-AZK01-126_Gate-of-Echoed-Waves-Gate_G_G_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-127',
  'Sundering Strike',
  'UC',
  NULL,
  'LIGHTNING',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Samurai'],
  '[Response] Deal 1 damage to an entity in your opponent''s Garden.',
  NULL,
  'S1-AZK01-127_Sundering-Strike_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-128',
  'Wrong Step',
  'UC',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Earthfury', 'Obsidian'],
  '[Response] Destroy an attacking entity with a health of 2 or less.',
  NULL,
  'S1-AZK01-128_Wrong-Step_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-129',
  'Silk Tongue Veyla',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  4,
  1,
  5,
  ARRAY['Defender'],
  ARRAY['Black Jade', 'Pyreskin', 'Wildfire'],
  'Defender. [Once/Turn] Whenever this entity takes or deals damage, deal 1 damage to all leaders.',
  NULL,
  'S1-AZK01-129_Silk-Tongue-Velya_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-001',
  'Bobu',
  'L',
  NULL,
  'EARTH',
  'LEADER',
  NULL,
  20,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Bobu', 'Brewmaster', 'Stonemend'],
  '[Once/Turn][Main] Pay 1 IKZ: Until the start of your next turn, the first time an Earth entity in your Garden or Alley is destroyed or sacrificed, you may heal 1 to your leader.',
  NULL,
  'S1-STT03-001A_Bobu_L_L_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-002',
  'Stonehaven Gate',
  'G',
  NULL,
  'EARTH',
  'GATE',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Portal an untapped entity from the Alley into the Garden, then you may give an entity in your Garden with base health equal to or less than the Gate Power of the portaled entity Defender until the start of your next turn.',
  NULL,
  'S1-STT03-002A_Stonehaven-Gate_G_G_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-003',
  'Koyama Farm Potter',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Artisan', 'Dusttracker'],
  '[On Play] Look at the top 5 cards of your deck, you may reveal up to 1 Verdant subtype card and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-STT03-003_Koyama-Farm-Potter_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-004',
  'Sloth Scarecrow',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  0,
  1,
  0,
  1,
  ARRAY['Defender'],
  ARRAY['Earthwarden', 'Stonemend'],
  'Defender. [Main] You may sacrifice this card: Heal 1 to your leader.',
  NULL,
  'S1-STT03-004_Sloth-Scarecrow_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-005',
  'Wobbly Cabbage Cart',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  0,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Earthfury'],
  '[When Destroyed] You may destroy an entity with 1 health in your opponent''s Garden.',
  NULL,
  'S1-STT03-005_Wobbly-Cabbage-Cart_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-006',
  'Cactus Farmer',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  2,
  1,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Earthwarden'],
  '[When Destroyed] Draw 1, then discard 1.',
  NULL,
  'S1-STT03-006_Cactus-Farmer_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-007',
  'Koyama Farm Caretaker',
  'R',
  NULL,
  'EARTH',
  'ENTITY',
  1,
  1,
  0,
  3,
  ARRAY[]::text[],
  ARRAY['Farmer', 'Verdant'],
  '[In Garden Only Ability] Treat this card also as an IKZ card. (This ability is not affected by Cooldown)',
  NULL,
  'S1-STT03-007_Koyama-Farm-Caretaker_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-008',
  'Midnight Courier',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Strider'],
  NULL,
  NULL,
  'S1-STT03-008_Midnight-Courier_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-009',
  'Warding Totem',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  0,
  2,
  2,
  4,
  ARRAY['Defender'],
  ARRAY['Earthwarden', 'Statue', 'Verdant'],
  'Defender. [On Play] Add 1 IKZ from your IKZ pile to your IKZ area; the IKZ enters the field tapped.',
  NULL,
  'S1-STT03-009_Warding-Totem_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-010',
  'Shroommancer',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  2,
  2,
  2,
  4,
  ARRAY[]::text[],
  ARRAY['Stonemend'],
  '[Once/Turn] Whenever this card attacks and destroys an entity in your opponent''s Garden, you may heal 1 to your leader.',
  NULL,
  'S1-STT03-010_Shroommancer_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-011',
  'Koyama Farm Plowman',
  'C',
  NULL,
  'EARTH',
  'ENTITY',
  3,
  3,
  3,
  5,
  ARRAY[]::text[],
  ARRAY['Earthwarden', 'Farmer', 'Obsidian'],
  '[On Play] If this card is played in the Garden, you may destroy an entity with a base health of 2 or less in your opponent''s Garden.',
  NULL,
  'S1-STT03-011_Koyama-Farm-Plowman_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-012',
  'Miharu of the White Bloom',
  'SR',
  NULL,
  'EARTH',
  'ENTITY',
  3,
  3,
  3,
  6,
  ARRAY[]::text[],
  ARRAY['Stonemend', 'Verdant'],
  '[On Play] You may play an entity with a cost of 2 or less from your hand into your Garden. [In Garden Only Ability][Once/Turn] On your opponent''s turn, whenever another entity in your Garden or this entity is destroyed, you may heal 2 to your leader.',
  NULL,
  'S1-STT03-012_Miharu-of-the-White-Bloom_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-013',
  'Stone Masked Ancient',
  'SR',
  NULL,
  'EARTH',
  'ENTITY',
  3,
  6,
  3,
  7,
  ARRAY[]::text[],
  ARRAY['Obsidian', 'Sandstrider'],
  '[In Garden Only Ability] Taunt. (When tapped, opponents can only attack entities with Taunt.) When this card enters the Garden, you may tap it.',
  NULL,
  'S1-STT03-013A_Stone-Masked-Ancient_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-014',
  'Sandcoil Python',
  'UC',
  NULL,
  'EARTH',
  'ENTITY',
  6,
  6,
  4,
  8,
  ARRAY[]::text[],
  ARRAY['Rootbane', 'Sandstrider', 'Verdant'],
  '[On Play] All entities in your opponent''s Garden with a base attack of 3 or less become Rooted. (Cannot attack until the start of your next turn.)',
  NULL,
  'S1-STT03-014_Sandcoil-Python_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-015',
  'Jar of Beans',
  'UC',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Stonemend'],
  '[Main] Heal 3 to your leader. If you have 7 or more IKZ in your IKZ area, heal 5 instead.',
  NULL,
  'S1-STT03-015_Jar-of-Beans_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT03-016',
  'Quicksand',
  'R',
  NULL,
  'EARTH',
  'SPELL',
  NULL,
  NULL,
  NULL,
  5,
  ARRAY[]::text[],
  ARRAY['Earthfury'],
  '[Main] Destroy all entities with 2 health or less in your opponent''s Garden.',
  NULL,
  'S1-STT03-016_Quicksand_S_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-001',
  'Zero',
  'L',
  NULL,
  'FIRE',
  'LEADER',
  NULL,
  20,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY['Black Jade', 'Scorchweaver'],
  '[Once/Turn][Main] Deal 1 damage to this card: Deal 1 damage to an entity in your Garden or Alley, then give that entity +1 attack until the end of the turn.',
  NULL,
  'S1-STT04-001_Zero_L_L_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-002',
  'Ragefire Gate',
  'G',
  NULL,
  'FIRE',
  'GATE',
  NULL,
  NULL,
  NULL,
  NULL,
  ARRAY[]::text[],
  ARRAY[]::text[],
  'Portal an untapped entity from the Alley into the Garden, then you may give an entity in your Garden that took damage this turn +Attack equal to the Gate Power of the portaled entity until the end of the turn.',
  NULL,
  'S1-STT04-002A_Ragefire-Gate_G_G_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-003',
  'Cinderwake Seer',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  2,
  0,
  1,
  ARRAY[]::text[],
  ARRAY['Blazerker', 'Cinderwake'],
  '[Start of Each Turn] You must deal 1 damage to this card.',
  NULL,
  'S1-STT04-003_Cinderwake-Seer_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-004',
  'Fanatic Kindler',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  2,
  0,
  1,
  ARRAY[]::text[],
  ARRAY['Scorchweaver'],
  '[On Play] You may sacrifice this card: Deal 1 damage to an entity in any Garden.',
  NULL,
  'S1-STT04-004_Fanatic-Kindler_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-005',
  'Ruby',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  1,
  1,
  1,
  ARRAY[]::text[],
  ARRAY['Ashveil'],
  '[On Play] Look at the top 5 cards of your deck, reveal up to 1 Pyreskin subtype card and add it to your hand, then bottom deck the rest in any order.',
  NULL,
  'S1-STT04-005_Ruby_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-006',
  'Wolf Cub',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  2,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Dawnling', 'Wolf'],
  NULL,
  NULL,
  'S1-STT04-006_Wolf-Cub_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-007',
  'Enraged Howler',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  2,
  1,
  2,
  ARRAY[]::text[],
  ARRAY['Pyreskin', 'Wolf'],
  '[Once/Turn] Whenever this entity takes damage, it gets +1 attack until the end of turn.',
  NULL,
  'S1-STT04-007_Enraged-Howler_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-008',
  'Lady Emberheart',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  2,
  2,
  0,
  3,
  ARRAY[]::text[],
  ARRAY['Crimsondrift'],
  '[Once/Turn] On your turn, after this card attacks an entity, you may untap this card.',
  NULL,
  'S1-STT04-008_Lady-Emberheart_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-009',
  'Cinderwake Ritualist',
  'R',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  2,
  2,
  3,
  ARRAY[]::text[],
  ARRAY['Cinderwake', 'Pyreskin'],
  '[In Garden Only Ability][Once/Turn] Whenever this card takes damage from card effects, you may also deal that damage to another leader or entity in any Garden, capped at 2 damage.',
  NULL,
  'S1-STT04-009_Cinderwake-Ritualist_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-010',
  'Reckless Tinkerer',
  'C',
  NULL,
  'FIRE',
  'ENTITY',
  1,
  2,
  1,
  3,
  ARRAY['Charge'],
  ARRAY['Blazerker', 'Elder', 'Pyreskin'],
  'Charge (Can attack the same turn it enters the Garden). [On Play] You must deal 1 damage to this card.',
  NULL,
  'S1-STT04-010_Reckless-Tinkerer_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-011',
  'Scorchland Raven',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  2,
  3,
  4,
  ARRAY[]::text[],
  ARRAY['Bird'],
  NULL,
  NULL,
  'S1-STT04-011_Scorchland-Raven_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-012',
  'Spiteful Raider',
  'UC',
  NULL,
  'FIRE',
  'ENTITY',
  3,
  2,
  1,
  4,
  ARRAY[]::text[],
  ARRAY['Bandit', 'Pyreskin'],
  '[Once/Turn] Whenever this card takes damage, deal 1 damage to a leader or an entity in any Garden.',
  NULL,
  'S1-STT04-012_Spiteful-Raider_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-013',
  'Kurai the Volcano',
  'SR',
  NULL,
  'FIRE',
  'ENTITY',
  3,
  3,
  2,
  5,
  ARRAY[]::text[],
  ARRAY['Crimsondrift', 'Elder'],
  '[Once/Turn] Whenever an entity in your opponent''s Garden is destroyed, untap this card.',
  NULL,
  'S1-STT04-013_Kurai-the-Volcano_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-014',
  'Scorchveil Shinobi, Suzuka',
  'SR',
  NULL,
  'FIRE',
  'ENTITY',
  3,
  3,
  1,
  6,
  ARRAY['Charge'],
  ARRAY['Blazerker', 'Ninja'],
  'Charge (Can attack the same turn it enters the Garden). [On Play] If your leader has the Scorchweaver subtype, deal 1 damage to all entities in each player''s Garden, then give all other entities in your Garden +1 attack until the end of the turn.',
  NULL,
  'S1-STT04-014A_Scorchveil-Shinobi-Suzuka_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-015',
  'Detonation Pact',
  'C',
  NULL,
  'FIRE',
  'SPELL',
  NULL,
  NULL,
  NULL,
  1,
  ARRAY[]::text[],
  ARRAY['Scorchweaver'],
  '[Main] Deal 1 damage to your leader: Deal 2 damage to your opponent''s leader.',
  NULL,
  'S1-STT04-015_Detonation-Pact_S_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-016',
  'Collateral Burst',
  'UC',
  NULL,
  'FIRE',
  'SPELL',
  NULL,
  NULL,
  NULL,
  2,
  ARRAY[]::text[],
  ARRAY['Pyreskin', 'Scorchweaver'],
  '[Main] Deal 1 damage to an entity in your Garden: Deal up to 2 damage to a leader or an entity in your opponent''s Garden.',
  NULL,
  'S1-STT04-016_Collateral-Burst_S_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'STT04-017',
  'Wrath of Sinder',
  'R',
  NULL,
  'FIRE',
  'SPELL',
  NULL,
  NULL,
  NULL,
  3,
  ARRAY[]::text[],
  ARRAY['Blazerker'],
  '[Main] Sacrifice any number of entities in your Garden: Deal damage to an entity or a leader in any Garden equal to the number of entities sacrificed.',
  NULL,
  'S1-STT04-017_Wrath-of-Sinder_S_R_die.jpg'
);
