INSERT INTO "cards" (
  "id", "card_code", "name", "rarity", "special_rarity", "element", "card_type",
  "attack", "health", "gate_points", "ikz_cost", "keywords", "subtypes",
  "effect_text", "flavor_text", "image_url"
) VALUES
(
  gen_random_uuid()::uuid,
  'AZK01-013',
  'Gou the Iron Judge',
  'UC',
  NULL,
  'NORMAL',
  'ENTITY',
  3,
  3,
  1,
  5,
  ARRAY[]::text[],
  ARRAY['Fatedealer'],
  '[On Play] Your opponent chooses 1: Sacrifice an entity in their Garden or discard 2.',
  NULL,
  '/cards/S1-AZK01-013_Gou-the-Iron-Judge_E_UC_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-076',
  'Hōren of Two Paths',
  'C',
  NULL,
  'NORMAL',
  'ENTITY',
  1,
  2,
  1,
  3,
  ARRAY[]::text[],
  ARRAY['Fatedealer', 'Monk'],
  '[On Play] Your opponent chooses 1: - This entity gains Charge (Can attack the same turn it enters the Garden) until the end of the turn. - Heal 2 to your leader.',
  NULL,
  '/cards/S1-AZK01-076_Horen-of-Two-Paths_E_C_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-079',
  'Gin and Tonika',
  'SR',
  NULL,
  'NORMAL',
  'ENTITY',
  3,
  4,
  3,
  6,
  ARRAY[]::text[],
  ARRAY['Fatedealer'],
  '[On Play] Your opponent chooses 1: You draw 2 or deal 3 damage to their leader.',
  NULL,
  '/cards/S1-AZK01-079_Gin-and-Tonika_E_SR_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-083',
  'Gurugumi Imitator',
  'R',
  NULL,
  'NORMAL',
  'ENTITY',
  2,
  2,
  1,
  4,
  ARRAY[]::text[],
  ARRAY['Gurijutsu'],
  '[Once/Turn][Main] This card gets the card text of another (Neutral) card in your Garden until the end of your turn.',
  NULL,
  '/cards/S1-AZK01-083_Gurugumi-Imitator_E_R_die.jpg'
),
(
  gen_random_uuid()::uuid,
  'AZK01-099',
  'Raiko''s Wrath, Shin',
  'SR',
  NULL,
  'LIGHTNING',
  'ENTITY',
  4,
  4,
  3,
  7,
  ARRAY[]::text[],
  ARRAY['Shockcoil', 'Stormcaller', 'Tiger'],
  '[On Play] Choose one: - An entity with a cost of 5 or less in your opponent''s Garden becomes "Shocked" (Does not untap during its next untap phase). - This entity gains Charge (Can attack the same turn it enters the Garden) until the end of the turn.',
  NULL,
  '/cards/S1-AZK01-099_Raikos-Wrath-Shin_E_SR_die.jpg'
)
ON CONFLICT ("card_code", "rarity", "special_rarity") DO NOTHING;
