#include "validation/action_schema.h"

#include "constants/game.h"

#define UNUSED_PARAM { AZK_ACTION_PARAM_UNUSED, 0, 0 }

#define HAND_INDEX_PARAM { AZK_ACTION_PARAM_HAND_INDEX, 0, MAX_HAND_SIZE - 1 }
#define GARDEN_INDEX_PARAM { AZK_ACTION_PARAM_GARDEN_INDEX, 0, GARDEN_SIZE - 1 }
#define GARDEN_OR_LEADER_PARAM { AZK_ACTION_PARAM_GARDEN_OR_LEADER_INDEX, 0, GARDEN_SIZE }
#define ALLEY_INDEX_PARAM { AZK_ACTION_PARAM_ALLEY_INDEX, 0, ALLEY_SIZE - 1 }
#define BOOL_PARAM { AZK_ACTION_PARAM_BOOL, 0, 1 }
#define ABILITY_ZONE_PARAM { AZK_ACTION_PARAM_ABILITY_ZONE, 0, 4 }
#define ABILITY_SLOT_PARAM { AZK_ACTION_PARAM_ABILITY_SLOT, 0, MAX_HAND_SIZE - 1 }
#define PLAYER_INDEX_PARAM { AZK_ACTION_PARAM_PLAYER_INDEX, 0, MAX_PLAYERS_PER_MATCH - 1 }
#define TARGET_ZONE_KIND_PARAM { AZK_ACTION_PARAM_TARGET_ZONE_KIND, 0, 2 }

static const AzkActionSpec ACTION_SPECS[] = {
  {
    .type = ACT_NOOP,
    .phase_mask = AZK_PHASE_MASK(PHASE_PREGAME_MULLIGAN) | AZK_PHASE_MASK(PHASE_MAIN),
    .params = { UNUSED_PARAM, UNUSED_PARAM, UNUSED_PARAM }
  },
  {
    .type = ACT_PLAY_ENTITY_TO_GARDEN,
    .phase_mask = AZK_PHASE_MASK(PHASE_MAIN),
    .params = { HAND_INDEX_PARAM, GARDEN_INDEX_PARAM, BOOL_PARAM }
  },
  {
    .type = ACT_PLAY_ENTITY_TO_ALLEY,
    .phase_mask = AZK_PHASE_MASK(PHASE_MAIN),
    .params = { HAND_INDEX_PARAM, GARDEN_INDEX_PARAM, BOOL_PARAM }
  },
  {
    .type = ACT_ATTACH_WEAPON_FROM_HAND,
    .phase_mask = AZK_PHASE_MASK(PHASE_MAIN),
    .params = { HAND_INDEX_PARAM, GARDEN_OR_LEADER_PARAM, BOOL_PARAM }
  },
  {
    .type = ACT_GATE_PORTAL,
    .phase_mask = AZK_PHASE_MASK(PHASE_MAIN),
    .params = { ALLEY_INDEX_PARAM, GARDEN_INDEX_PARAM, UNUSED_PARAM }
  },
  {
    .type = ACT_ATTACK,
    .phase_mask = AZK_PHASE_MASK(PHASE_MAIN),
    .params = { GARDEN_OR_LEADER_PARAM, GARDEN_OR_LEADER_PARAM, UNUSED_PARAM }
  },
  {
    .type = ACT_MULLIGAN_SHUFFLE,
    .phase_mask = AZK_PHASE_MASK(PHASE_PREGAME_MULLIGAN),
    .params = { UNUSED_PARAM, UNUSED_PARAM, UNUSED_PARAM }
  },
  {
    .type = ACT_ACTIVATE_ABILITY,
    .phase_mask = AZK_PHASE_MASK(PHASE_MAIN) | AZK_PHASE_MASK(PHASE_RESPONSE_WINDOW),
    .params = { ABILITY_ZONE_PARAM, ABILITY_SLOT_PARAM, BOOL_PARAM }
  },
  {
    .type = ACT_SELECT_COST_TARGET,
    .phase_mask = AZK_PHASE_MASK(PHASE_START_OF_TURN) |
                  AZK_PHASE_MASK(PHASE_MAIN) |
                  AZK_PHASE_MASK(PHASE_RESPONSE_WINDOW) |
                  AZK_PHASE_MASK(PHASE_COMBAT_RESOLVE) |
                  AZK_PHASE_MASK(PHASE_END_TURN_ACTION) |
                  AZK_PHASE_MASK(PHASE_END_TURN),
    .params = { PLAYER_INDEX_PARAM, TARGET_ZONE_KIND_PARAM, GARDEN_OR_LEADER_PARAM }
  },
  {
    .type = ACT_SELECT_EFFECT_TARGET,
    .phase_mask = AZK_PHASE_MASK(PHASE_START_OF_TURN) |
                  AZK_PHASE_MASK(PHASE_MAIN) |
                  AZK_PHASE_MASK(PHASE_RESPONSE_WINDOW) |
                  AZK_PHASE_MASK(PHASE_COMBAT_RESOLVE) |
                  AZK_PHASE_MASK(PHASE_END_TURN_ACTION) |
                  AZK_PHASE_MASK(PHASE_END_TURN),
    .params = { PLAYER_INDEX_PARAM, TARGET_ZONE_KIND_PARAM, GARDEN_OR_LEADER_PARAM }
  },
  {
    .type = ACT_ACCEPT_TRIGGERED_ABILITY,
    .phase_mask = AZK_PHASE_MASK(PHASE_START_OF_TURN) |
                  AZK_PHASE_MASK(PHASE_MAIN) |
                  AZK_PHASE_MASK(PHASE_RESPONSE_WINDOW) |
                  AZK_PHASE_MASK(PHASE_COMBAT_RESOLVE) |
                  AZK_PHASE_MASK(PHASE_END_TURN_ACTION) |
                  AZK_PHASE_MASK(PHASE_END_TURN),
    .params = { UNUSED_PARAM, UNUSED_PARAM, UNUSED_PARAM }
  }
};

const AzkActionSpec *azk_get_action_specs(size_t *out_count) {
  if (out_count) {
    *out_count = sizeof(ACTION_SPECS) / sizeof(ACTION_SPECS[0]);
  }
  return ACTION_SPECS;
}
