"""Generate azuki_jax card tables from src/generated/card_defs.c.

Parses the generated C card definitions (the ground truth used by the engine)
and emits jax_env/azuki_jax/cards_generated.py with plain-Python tables in
card-def-id order. Re-run whenever card_defs.c changes.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CARD_DEFS_C = REPO / "src" / "generated" / "card_defs.c"
OUT_PATH = REPO / "jax_env" / "azuki_jax" / "cards_generated.py"

RARITIES = ["L", "G", "C", "UC", "R", "SR", "IKZ"]
ELEMENTS = ["NORMAL", "LIGHTNING", "WATER", "EARTH", "FIRE"]
TYPES = ["LEADER", "GATE", "ENTITY", "WEAPON", "SPELL", "IKZ", "EXTRA_IKZ"]

KEYWORD_TAGS = [
    "Charge",
    "Defender",
    "EffectImmune",
    "Godmode",
    "Taunt",
    "Rooted",
    "Infiltrate",
]
ATTR_TAGS = [
    "AttrCanTargetTappedAndUntappedAlley",
    "AttrGardenForceTapped",
    "AttrCountsAsIkzSource",
    "AttrCanTargetLeaderOnly",
]


def parse_card_defs(text: str) -> list[dict]:
  """Parse the kGeneratedCardDefs array entries, in order."""
  array_match = re.search(
      r"static const CardDef kGeneratedCardDefs\[CARD_DEF_COUNT\] = \{(.*?)\n\};",
      text,
      re.S,
  )
  if not array_match:
    raise RuntimeError("kGeneratedCardDefs array not found")
  body = array_match.group(1)

  cards = []
  for entry in re.finditer(r"\{\s*\.card_id = \"([^\"]+)\",(.*?)\n    \},", body, re.S):
    code, fields = entry.group(1), entry.group(2)

    def grab(pattern: str) -> str:
      m = re.search(pattern, fields)
      if not m:
        raise RuntimeError(f"pattern {pattern!r} missing for card {code}")
      return m.group(1)

    cards.append(
        {
            "code": code,
            "name": grab(r"\.name = \"([^\"]*)\""),
            "rarity": grab(r"\.rarity = CARD_RARITY_(\w+)"),
            "element": grab(r"\.element = CARD_ELEMENT_(\w+)"),
            "type": grab(r"\.type = CARD_TYPE_(\w+)"),
            "has_base_stats": grab(r"\.has_base_stats = (\w+)") == "true",
            "base_atk": int(grab(r"\.attack = (-?\d+)")),
            "base_hp": int(grab(r"\.health = (-?\d+)")),
            "has_gate_points": grab(r"\.has_gate_points = (\w+)") == "true",
            "gate_points": int(grab(r"\.gate_points = \{ \.gate_points = (\d+)")),
            "has_ikz_cost": grab(r"\.has_ikz_cost = (\w+)") == "true",
            "ikz_cost": int(grab(r"\.ikz_cost = \{ \.ikz_cost = (-?\d+)")),
        }
    )
  return cards


def parse_prefabs(text: str, cards: list[dict]) -> None:
  """Augment cards with prefab data: subtypes, inherent tags, condition presets."""
  by_code = {card["code"]: card for card in cards}
  for card in cards:
    card["subtypes"] = []
    card["keywords"] = []
    card["attrs"] = []
    card["cond_effect_immune"] = 0

  for block in re.finditer(
      r"\.name = \"CardPrefab::([^\"]+)\",\s*\.add = \(ecs_id_t\[\]\)\{ EcsPrefab, ([^}]*)\}"
      r"(.*?)(?=\.name = \"CardPrefab::|\Z)",
      text,
      re.S,
  ):
    code, add_list, body = block.group(1), block.group(2), block.group(3)
    card = by_code.get(code)
    if card is None:
      raise RuntimeError(f"prefab for unknown card {code}")

    tags = [tag.strip() for tag in add_list.split(",") if tag.strip() and tag.strip() != "0"]
    for tag in tags:
      if tag in KEYWORD_TAGS:
        card["keywords"].append(tag)
      elif tag in ATTR_TAGS:
        card["attrs"].append(tag)
      elif tag.startswith("T"):
        pass  # card-type tag, already captured from defs array
      else:
        raise RuntimeError(f"unknown prefab tag {tag!r} on {code}")

    for sub in re.finditer(r"ecs_add\(world, prefab, TSubtype_(\w+)\);", body):
      card["subtypes"].append(sub.group(1))

    cond = re.search(
        r"ecs_set\(world, prefab, CardConditionCountdown, \{([^}]*)\}", body
    )
    if cond:
      immune = re.search(r"\.effect_immune_duration = (-?\d+)", cond.group(1))
      if immune:
        card["cond_effect_immune"] = int(immune.group(1))


def emit(cards: list[dict]) -> str:
  subtype_vocab = sorted({sub for card in cards for sub in card["subtypes"]})
  subtype_index = {name: i for i, name in enumerate(subtype_vocab)}

  lines = [
      '"""Card definition tables generated from src/generated/card_defs.c.',
      "",
      "Auto-generated by jax_env/tools/gen_card_tables.py. Do not edit manually.",
      '"""',
      "",
      f"CARD_DEF_COUNT = {len(cards)}",
      f"RARITIES = {RARITIES!r}",
      f"ELEMENTS = {ELEMENTS!r}",
      f"TYPES = {TYPES!r}",
      f"SUBTYPES = {subtype_vocab!r}",
      f"KEYWORD_TAGS = {KEYWORD_TAGS!r}",
      f"ATTR_TAGS = {ATTR_TAGS!r}",
      "",
      "# Per-card tables, indexed by CardDefId (enum order in card_defs.h).",
  ]

  def col(name: str, values: list) -> None:
    lines.append(f"{name} = {values!r}")

  col("CARD_CODES", [card["code"] for card in cards])
  col("CARD_NAMES", [card["name"] for card in cards])
  col("CARD_RARITY", [RARITIES.index(card["rarity"]) for card in cards])
  col("CARD_ELEMENT", [ELEMENTS.index(card["element"]) for card in cards])
  col("CARD_TYPE", [TYPES.index(card["type"]) for card in cards])
  col("CARD_HAS_BASE_STATS", [int(card["has_base_stats"]) for card in cards])
  col("CARD_BASE_ATK", [card["base_atk"] for card in cards])
  col("CARD_BASE_HP", [card["base_hp"] for card in cards])
  col("CARD_HAS_GATE_POINTS", [int(card["has_gate_points"]) for card in cards])
  col("CARD_GATE_POINTS", [card["gate_points"] for card in cards])
  col("CARD_HAS_IKZ_COST", [int(card["has_ikz_cost"]) for card in cards])
  col("CARD_IKZ_COST", [card["ikz_cost"] for card in cards])
  col(
      "CARD_SUBTYPE_MASK",
      [
          sum(1 << subtype_index[sub] for sub in card["subtypes"])
          for card in cards
      ],
  )
  for tag in KEYWORD_TAGS:
    col(
        f"CARD_INHERENT_{tag.upper()}",
        [int(tag in card["keywords"]) for card in cards],
    )
  for tag in ATTR_TAGS:
    short = tag.removeprefix("Attr").upper()
    col(f"CARD_{short}", [int(tag in card["attrs"]) for card in cards])
  col("CARD_COND_EFFECT_IMMUNE", [card["cond_effect_immune"] for card in cards])

  lines.append("")
  return "\n".join(lines)


def main() -> None:
  text = CARD_DEFS_C.read_text()
  cards = parse_card_defs(text)
  if len(cards) != 193:
    raise RuntimeError(f"expected 193 cards, parsed {len(cards)}")
  parse_prefabs(text, cards)
  OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
  OUT_PATH.write_text(emit(cards))
  print(f"wrote {OUT_PATH} ({len(cards)} cards)")


if __name__ == "__main__":
  main()
