"""Generate ability registry tables from src/abilities/ability_registry.c.

Emits jax_env/azuki_jax/abilities/registry_generated.py: one entry per
(card_def_id, slot) with all AbilityDef data fields plus the C function-pointer
NAMES (which key into hand-written JAX implementations).
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "src" / "abilities" / "ability_registry.c"
OUT = REPO / "jax_env" / "azuki_jax" / "abilities" / "registry_generated.py"

BOOL_FIELDS = [
    "has_ability",
    "is_optional",
    "is_once_per_turn",
    "can_play_as_response_from_hand",
    "can_select_to_garden",
    "can_select_to_alley",
    "can_select_to_equip",
    "selection_to_equip_is_reequip",
    "can_select_to_hand",
    "selection_pick_is_optional",
    "clear_selection_if_still_active",
    "can_topdeck_selection",
]
FN_FIELDS = [
    "validate",
    "validate_cost_target",
    "validate_effect_target",
    "apply_costs",
    "apply_effects",
    "on_cost_paid",
    "validate_selection_target",
    "on_selection_complete",
    "init_passive_observers",
    "cleanup_passive_observers",
]


def strip_line_comments(text: str) -> str:
  """Remove // comments so regexes can span commented struct fields."""
  return re.sub(r"//[^\n]*", "", text)


_COUNT_MACROS = {
    "GARDEN_SIZE": 5,
    "ALLEY_SIZE": 5,
    "MAX_HAND_SIZE": 30,
    "MAX_ABILITY_SELECTION": 8,
    "IKZ_AREA_SIZE": 10,
}


def _resolve_count(token: str, code: str, scope: str) -> int:
  if token.isdigit():
    return int(token)
  if token in _COUNT_MACROS:
    return _COUNT_MACROS[token]
  raise RuntimeError(f"unknown count token {token!r} in {code} {scope}")


def parse_entries(text: str):
  text = strip_line_comments(text)
  entries = []
  # Matches both kAbilityRegistry[CARD_DEF_X] and
  # kAdditionalAbilityRegistry[CARD_DEF_X][n]
  pattern = re.compile(
      r"k(Additional)?AbilityRegistry\[CARD_DEF_(\w+)\](?:\[(\d+)\])?\s*=\s*\(AbilityDef\)\{(.*?)\n  \};",
      re.S,
  )
  for m in pattern.finditer(text):
    additional, code, slot_str, body = m.groups()
    slot = int(slot_str) + 1 if additional else 0
    entry: dict = {"code": code, "slot": slot}
    for field in BOOL_FIELDS:
      fm = re.search(rf"\.{field}\s*=\s*(true|false)", body)
      entry[field] = bool(fm and fm.group(1) == "true")
    ikz = re.search(r"\.ikz_cost\s*=\s*(-?\d+)", body)
    entry["ikz_cost"] = int(ikz.group(1)) if ikz else 0
    for scope in ("cost_req", "effect_req"):
      sm = re.search(
          rf"\.{scope}\s*=\s*\{{\s*\.type\s*=\s*ABILITY_TARGET_(\w+),\s*"
          rf"\.min\s*=\s*(\w+),\s*\.max\s*=\s*(\w+)",
          body,
      )
      if sm:
        entry[scope] = (
            sm.group(1),
            _resolve_count(sm.group(2), code, scope),
            _resolve_count(sm.group(3), code, scope),
        )
      else:
        if re.search(rf"\.{scope}\s*=", body):
          raise RuntimeError(f"unparsed {scope} for {code}")
        entry[scope] = ("NONE", 0, 0)
    for tag_field in ("timing_tag", "secondary_timing_tag"):
      tm = re.search(rf"\.{tag_field}\s*=\s*ecs_id\((\w+)\)", body)
      entry[tag_field] = tm.group(1) if tm else None
    for fn in FN_FIELDS:
      fm = re.search(rf"\.{fn}\s*=\s*(\w+)", body)
      name = fm.group(1) if fm else None
      entry[fn] = None if name in (None, "NULL") else name
    entries.append(entry)
  return entries


def main() -> None:
  text = SRC.read_text()
  entries = parse_entries(text)
  if not entries:
    raise RuntimeError("no registry entries parsed")
  OUT.parent.mkdir(parents=True, exist_ok=True)
  lines = [
      '"""Ability registry parsed from src/abilities/ability_registry.c.',
      "",
      "Auto-generated by jax_env/tools/gen_ability_registry.py. Do not edit.",
      '"""',
      "",
      "# One dict per (card, slot); slot 0 = primary, 1.. = additional registry.",
      f"ENTRIES = {entries!r}",
      "",
  ]
  OUT.write_text("\n".join(lines))
  primary = sum(1 for entry in entries if entry["slot"] == 0)
  print(f"wrote {OUT}: {len(entries)} entries ({primary} primary)")


if __name__ == "__main__":
  main()
